config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'sign_up' }

  namespace :admin do
    root 'events#index'
    resources :events, path: "eventos" do
      get "report"
      collection do 
        get "search"
      end
      resources :researches, path: "pesquisas" do
        get "report"
        resources :identifiers, path: "identificadores"
        resources :surveys, path: "questionarios", param: :number_survey do
            match 'answers' => 'answers#new', via: :get, path: "respostas"
            match 'answers' => 'answers#create', via: :post, path: "respostas"
            match 'answers' => 'answers#update', via: :patch, path: "respostas"
            match 'answers' => 'answers#update', via: :put, path: "respostas"
            
            collection do
              resources :survey_participants, path: 'participantes'
              match 'import' => 'import_surveys#index',  via: :get, path: "importar"
              match 'import' => 'import_surveys#import', via: :post, path: "importar"
            end
        end
        member do
          match 'groups' => 'groups#index', via: :get, path: "perguntas"
          match 'groups' => 'groups#create', via: :post, path: "perguntas"
          match 'groups' => 'groups#update', via: :patch, path: "perguntas"
          match 'groups' => 'groups#update', via: :put, path: "perguntas"
        end
      end 
    end
    resources :users, path: "usuarios"
  end

  namespace :ajax do 
    get "report", to: "report#index"
    get "identifiers", to: "report#identifiers"
  end

  root 'home#index'
  
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  belongs_to :research
  
  belongs_to :participant, class_name: "User"

  has_many :answers, dependent: :destroy

  has_many :survey_identifiers, dependent: :destroy
  has_many :identifiers, through: :survey_identifiers

  belongs_to :author, class_name: "User"

  paginates_per 15

  accepts_nested_attributes_for :answers
  accepts_nested_attributes_for :survey_identifiers
  accepts_nested_attributes_for :identifiers

  validates :number_survey, uniqueness: {scope: :research_id, message: "Questionário ja cadastrado"}, presence: true, allow_blank: false

  def to_param
  	"#{number_survey}"
  end

  def self.by_research(research_id)
    where("research_id = ?", research_id)
  end

  def self.for_tasker(research_id, user)
    where("research_id = ? and participant_id = ?", research_id, user)
  end

  def self.filter(de, ate)
    if first.number_survey.to_i != 0
      where("(number_survey)::INT between ? and ?", research_id, user, number_survey, de, ate)
    else
      where("research_id = ? and participant_id: ? and number_survey between ? and ?", research_id, user, number_survey, de, ate)
    end
  end

  def self.search(search)
    if first.number_survey.to_i !=0
      where("(number_survey)::INT = ?", search)
    else
      where("number_survey like ?", "%#{search}%")
    end
  end
end

app/controllers/admin/surveys_controller.rb
class Admin::SurveysController < Admin::AdminController
	load_and_authorize_resource
	skip_load_resource :only => [:create]

	before_action :set_event_identifier_research, only: [:show, :edit, :new, :index, :create, :destroy, :update, :participants]
	before_action :set_survey, only: [:show, :edit, :update, :destroy, :participants]
	before_action :get_surveys, only: [:index, :create, :update]

	def index
		add_breadcrumb "Eventos", :admin_events_path
    add_breadcrumb "#{@event.title}", :admin_events_path
    add_breadcrumb "#{@research.title}", :admin_event_researches_path
    add_breadcrumb "Questionários", :admin_event_research_surveys_path

	end

	def show
	end

	def new
		add_breadcrumb "Eventos", :admin_events_path
    add_breadcrumb "#{@event.title}", :admin_events_path
    add_breadcrumb "#{@research.title}", :admin_event_researches_path
    add_breadcrumb "Questionários", :admin_event_research_surveys_path
    add_breadcrumb "Criar Questionário"
    
		@survey = Survey.new
		
		if !@research.identifiers.any?
			redirect_to admin_event_research_surveys_path(@event, @research), alert: 'Antes de criar um Questionário você deve criar um Identificador'
		end
	end

	def edit
		add_breadcrumb "Eventos", :admin_events_path
    add_breadcrumb "#{@event.title}", :admin_events_path
    add_breadcrumb "#{@research.title}", :admin_event_researches_path
    add_breadcrumb "Questionários", :admin_event_research_surveys_path
    add_breadcrumb "#{@survey.number_survey}", :admin_event_research_surveys_path
    add_breadcrumb "Editar", :edit_admin_event_research_survey_path
	end

	def create

		survey_identifiers = params[:survey][:identifiers]
		p "--------------#{survey_identifiers}"
		@survey = Survey.new
		survey_identifier = SurveyIdentifier.new

		@survey.id = Survey.last.id+1
		@survey.research_id = @research.id
		@survey.author_id = current_user.id
		number_survey = ""
		
		survey_identifiers.each_with_index do |item, index|
			if index == survey_identifiers.size-1
				number_survey << item[1]
			else
				number_survey << item[1]+"-"
			end			
		end
		
		@survey.number_survey = number_survey

		respond_to do |format|
			if @survey.save
				
				survey_identifiers.each_with_index do |item, index|
					SurveyIdentifier.create(id: SurveyIdentifier.last.id+1, survey: @survey, identifier_id: item[0].to_i, value: item[1])
				end
				if @surveys.respond_to? :num_pages
					format.html { redirect_to admin_event_research_surveys_path(@event, @research, page: @surveys.num_pages), notice: 'Questionário criado com sucesso' }
				else
					format.html { redirect_to admin_event_research_surveys_path(@event, @research, @surveys), notice: 'Questionário criado com sucesso' }
				end
			    format.json { render :show, status: :created, location: admin_event_research_survey_path(@event, @research, @survey) }
			else
				format.html { render :new }
        		format.json { render json: @surveys.errors, status: :unprocessable_entity }
		   	end
		end
		
	end

	# PATCH/PUT /answers/1
	# PATCH/PUT /answers/1.json
	def update
		survey_identifiers = params[:survey][:identifiers]
		number_survey = ""
		survey_identifiers.each_with_index do |item, index|
			if index == survey_identifiers.size-1
				number_survey << item[1]
			else
				number_survey << item[1]+"-"
			end
		end

		if @survey.update(number_survey: number_survey, author_id: current_user.id)
			survey_identifiers.each_with_index do |item, index|
				@survey.survey_identifiers.find_by(identifier_id: item[0]).update(value: item[1])
			end
		end

		respond_to do |format|
		  	format.html { redirect_to admin_event_research_surveys_path(@event, @research, page: get_page(@survey, @surveys)), notice: 'Questionário atualizado com sucesso' }
        format.json { render :show, status: :ok, location: @answer }
		end
	end

	def destroy
		@survey.destroy
		respond_to do |format|
	      format.html { redirect_to admin_event_research_surveys_path, notice: 'Questionário removido com sucesso' }
	      format.json { head :no_content }
	    end
	end

	private
		# Use callbacks to share common setup or constraints between actions.
	    def set_survey	    	
	    	@survey = @research.surveys.find_by(number_survey: params[:number_survey])	    	
	    end

	    # Never trust parameters from the scary internet, only allow the white list through.
	    def answer_params
	      params.require(:survey).permit(identifiers: [])
	    end

	    def set_event_identifier_research
	      @event = Event.where(status: true).find(params[:event_id])
      	 @research = Research.find(params[:research_id])
	    end

	    def get_surveys
	    	if current_user.role == "Pesquisador"
					surveys = Survey.for_tasker(@research.id, current_user)
				else
					surveys = Survey.by_research(@research.id)
				end
				
				
				if !surveys.empty?
					if params[:search]
						p "search"
						if !params[:search].empty?
							p "search not empty"
							if !/\W/.match(surveys.first.number_survey)
								p "search int"
					      surveys = surveys.where("(number_survey)::INT = ?", params[:search])
					    else
					    	p "search text"
					      surveys = surveys.where("number_survey like ?", "%#{params[:search]}%")
					    end
				  	end
				  end

					if params[:de] or params[:ate]
						p "de ate"
						if !params[:de].empty? or !params[:ate].empty?
							p "de ate not empty"
							if !/\W/.match(surveys.first.number_survey)
								p "de ate int"
								if params[:ate].empty? 
									p "ate empty"
									p params[:de]
					      	surveys = surveys.where("(number_survey)::INT >= ?", params[:de])
					    	elsif params[:de].empty?
					    		p "de empty"
					    		surveys = surveys.where("(number_survey)::INT <= ?", params[:ate])
					      else
					      	p "de ate both empty"
					      	surveys = surveys.where("(number_survey)::INT between ? and ?", params[:de], params[:ate])
					      end
					    else
					    	p "de ate text"
					    	if params[:ate].empty?
					    		p "ate empty"
					    		surveys = surveys.where("number_survey >= ?", params[:de])
					    	elsif params[:de].empty?
					    		p "de empty"
					    		surveys = surveys.where("number_survey <= ?", params[:ate])
					    	else
					    		p "de ate both empty"
					      	surveys = surveys.where("number_survey between ? and ?", params[:de], params[:ate])
					    	end
					    end
				  	end
					end
					
					if params[:sort]
						if params[:sort].empty? or params[:sort] == "number_survey"
							if !/\W/.match(surveys.first.number_survey)
								@surveys = surveys.order("(number_survey)::INT").page params[:page]
							else
								@surveys = surveys.order("number_survey").page params[:page]
							end			
						elsif params[:sort] != "updated_at" and !/\W/.match(surveys.first.number_survey)
							@surveys = surveys.order("(#{params[:sort]})::INT").page params[:page]
						else
							@surveys = surveys.order("#{params[:sort]} DESC").page params[:page]
						end
					else
						if !/\W/.match(surveys.first.number_survey)
							@surveys = surveys.order("(number_survey)::INT").page params[:page]
						else
							@surveys = surveys.order("number_survey").page params[:page]
						end
					end
					@count = surveys.count
				else
					@surveys = surveys
				end
	    end
end

app/views/admin/surveys/_form.html.erb
<div class="row form">
  <div class="large-12 columns end">
  <%= simple_form_for([:admin, @event, @research, @survey]) do |f| %>

    <% if @survey.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

        <ul>
        <% @survey.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    
    <h5>Identificador</h5>
    
    <div class="large-6">
      <% @research.identifiers.each do |identifier| %>
        <%= hidden_field_tag "survey[identifiers][#{identifier.id}]", "#{identifier.id}"%>
        <%= label "survey[identifiers][#{identifier.id}]", identifier.name.humanize %>
        <% if !@survey.id.nil? %>
          <%= text_field_tag "survey[identifiers][#{identifier.id}]", @survey.survey_identifiers.find_by("survey_identifiers.identifier_id = #{identifier.id}").value, {required: true} %>
        <% else %>
          <%= text_field_tag "survey[identifiers][#{identifier.id}]", nil, {required: true} %>
        <% end %>
      <% end %>
    </div>

    <div class="row">
      <div class="large-3 small-6 medium-6 columns">
        <%= link_to 'Cancelar', admin_event_research_surveys_path, class: "button hollow radius alert" %>
      </div>
      <div class="large-3 small-6 medium-6 columns text-right end">
        <%= f.submit "Salvar", class: "button hollow radius" %>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/admin/surveys/_survey.html.erb
<tr>
  <td>
  	<%= survey.number_survey %>
  	<span><%= l survey.updated_at.to_date, format: :long %></span>
  </td>
  <td class="hide-for-small"><%= survey.participant.nil? ? '' :  survey.participant.name %></td>
  <td class="hide-for-small"><%= survey.author.nil? ? '' : survey.author.email%></td>
  <% if !survey.answers.any? %>
    <% if can? :new, Answer %>
      <td>
      	<%= link_to admin_event_research_survey_answers_path(@event, @research, survey) do %>
      		<span class="icon-icon_48585 radius" data-tooltip aria-haspopup="true" title="Responder"></span>
      	<% end %>
      </td>
    <% end %>
  <% elsif !survey.number_survey.nil? %>
    <% if can? :show, Answer %>
      <td>
      	<%= link_to admin_event_research_survey_answers_path(@event, @research, survey) do%>
      		<span class="icon-icon_48585 radius" data-tooltip aria-haspopup="true" title="Resposta"></span>
      	<% end %>
      </td>
    <% end %>
  <% end %>
  <% if can? :edit, Survey and !survey.number_survey.nil? %>
    <td>
    	<%= link_to edit_admin_event_research_survey_path(@event, @research, survey) do%>
    		<span class="icon-edit radius" data-tooltip aria-haspopup="true" title="Editar"></span>
    	<% end %>
    </td>
  <% end %>
  <% if can? :destory, Survey and !survey.number_survey.nil? %>
    <td>
    	<%= link_to admin_event_research_survey_path(@event, @research, survey), class: "sweet", data: { text: "Tem certeza que desejar excluir o questionário: #{survey.number_survey} ?", title: "Excluir", id: survey.id } do %>
    		<span class="icon-cancel radius"></span>
    	<% end %>
    </td>
  <% end %>
</tr>

app/views/admin/surveys/edit.html.erb
  <div class="row header">
    <div class="large-4 columns end ">
      <span class="icon-calendar"></span>
      <h6>Editar Quesitonário</h6>  
    </div>
  </div>
  <hr>

	<%= render 'form' %>

app/views/admin/surveys/index.html.erb
<div class="row header surveys">
  <div class="large-4 medium-3 small-12 columns">
    <span class="icon-clipboard"></span>
    <h6>Questionários</h6>  
  </div>
  <div class="large-8 medium-9   small-12 columns text-right">
    <% if can? :import, Admin::ImportSurveysController %>
      <%= link_to 'Importar', import_admin_event_research_surveys_path(@event, @research), class: "button tiny hollow radius icon-publish" %>
    <% end %>
    <% if can? :index, Admin::SurveyParticipantsController %>
      <%= link_to 'Pesquisadores', admin_event_research_survey_participants_path(@event, @research), :class => "button tiny hollow radius icon-users"%>
    <% end %>
    <% if can? :report, @research %>
      <%= link_to 'Relatório', admin_event_research_report_path, :class => "button tiny hollow radius icon-presentation" %>
    <% end %>
    <% if can? :new, Survey %>
      <%= link_to 'Criar Questionário', new_admin_event_research_survey_path, :class => "button tiny hollow radius icon-plus" %>
    <% end %>
  </div>  
</div>

<div class="row search surveys">
  <%= form_tag admin_event_research_surveys_path, method: "get", id: "searchable" do %>
    <div class="large-2 small-6 medium-2 column">
      <%= select_tag "de", options_from_collection_for_select(@surveys.limit(Survey.count), "number_survey", "number_survey"), class: 'radius large-10', prompt: "De" %>
    </div>
    <div class="large-1 divider columns"></div>
    <div class="large-2 small-6 medium-2 column">
      <%= select_tag "ate", options_from_collection_for_select(@surveys.limit(Survey.count), "number_survey", "number_survey"), class: 'radius large-9', prompt: "Até" %>
    </div>
    <div class="large-1 divider columns"></div>
    <div class="large-4 small-8 medium-4 columns">
      <%= text_field_tag "search", params[:search] ,placeholder: "Buscar Questionários ou pesquisadores", class: "radius", data: {type: "event"} %>
    </div>
    <div class="large-1 divider columns"></div>
    <div class="large-2 small-4 medium-3 columns end">
      <select class="radius" name="sort" id="sortable">
        <option value="">Ordenar por</option>
        <option value="updated_at">Data</option>
        <option value="number_survey">Identificador</option>
      </select>
    </div>
  <% end %>
</div>

<table class="large-12">
  <thead>
    <tr>
      <th>Identificador</th>
      <th class="hide-for-small">Pesquisador</th>
      <th class="hide-for-small">Autor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="content">
    <%= render @surveys %>
  </tbody>
</table>

<% if !@surveys.empty? %>
  <%= paginate @surveys, remote: true %>
<% end %>

app/views/admin/surveys/index.js.erb
$("#content").html("<%= escape_javascript(render(@surveys)) %>");
$('#paginator').html('<%= escape_javascript(paginate(@surveys, :remote => true)) %>');

app/views/admin/surveys/new.html.erb
  <div class="row header">
    <div class="large-4 columns end ">
      <span class="icon-calendar"></span>
      <h6>Novo Questionário</h6>  
    </div>
  </div>
  <hr>  

	<%= render 'form' %>

app/views/admin/surveys/show.html.erb
<div class="large-12 columns content">
  <ul class="breadcrumbs">
    <li><%= link_to @event.title, admin_events_path %></li>
    <li><%= link_to @research.title, admin_event_researches_path%></li>
    <li><%= link_to 'QUESTIONÁRIOS', admin_event_researches_path%></li>
  </ul>
  <div class="large-4 columns">
    <h3>Questionário</h3>
  </div>
  <div class="large-8 columns text-right">
    <%= link_to 'Novo Questionário', new_admin_event_research_survey_path, :class => "button tiny" %>
  </div>
  
  <p id="notice"><%= notice %></p>
  
  <% @survey.survey_identifiers.each do |sid| %>
    <p>
      <strong><%= sid.identifier.name.humanize %>: </strong>
      <%= sid.value %>
    </p>
  <% end %>

  <%= link_to 'Edit', edit_admin_event_research_survey_path(@event, @research, @survey), :class => "button tiny" %> |
  <%= link_to 'Back', admin_event_research_surveys_path, :class => "button tiny" %>

</div>