config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'sign_up' }

  namespace :admin do
    root 'events#index'
    resources :events, path: "eventos" do
      get "report"
      collection do 
        get "search"
      end
      resources :researches, path: "pesquisas" do
        get "report"
        resources :identifiers, path: "identificadores"
        resources :surveys, path: "questionarios", param: :number_survey do
            match 'answers' => 'answers#new', via: :get, path: "respostas"
            match 'answers' => 'answers#create', via: :post, path: "respostas"
            match 'answers' => 'answers#update', via: :patch, path: "respostas"
            match 'answers' => 'answers#update', via: :put, path: "respostas"
            
            collection do
              resources :survey_participants, path: 'participantes'
              match 'import' => 'import_surveys#index',  via: :get, path: "importar"
              match 'import' => 'import_surveys#import', via: :post, path: "importar"
            end
        end
        member do
          match 'groups' => 'groups#index', via: :get, path: "perguntas"
          match 'groups' => 'groups#create', via: :post, path: "perguntas"
          match 'groups' => 'groups#update', via: :patch, path: "perguntas"
          match 'groups' => 'groups#update', via: :put, path: "perguntas"
        end
      end 
    end
    resources :users, path: "usuarios"
  end

  namespace :ajax do 
    get "report", to: "report#index"
    get "identifiers", to: "report#identifiers"
  end

  root 'home#index'
  
end

app/controllers/admin/survey_participants_controller.rb
class Admin::SurveyParticipantsController < Admin::AdminController
	authorize_resource :class => Admin::SurveyParticipantsController

	before_action :set_survey_participant, only: [:show, :destroy, :edit]
	before_action :set_event_research, only: [:show, :edit, :new, :index, :create, :destroy, :update]
	before_action :set_users, only: [:new, :edit]

	def index
		add_breadcrumb "Eventos", :admin_events_path
    add_breadcrumb "#{@event.title}", :admin_events_path
    add_breadcrumb "#{@research.title}", :admin_event_researches_path
    add_breadcrumb "Questionários", :admin_event_research_surveys_path
    add_breadcrumb "Pesquisadores"

		if params[:search] and !params[:search].empty?
			user = User.find_by("LOWER(name) LIKE LOWER(?)", "#{params[:search]}%")
			@participants = @research.surveys.joins(:participant).select("count(participant_id) as total_survey, participant_id, name").where("surveys.participant_id = ?", user).group('participant_id, name').page params[:page]
		else
			@participants = @research.surveys.joins(:participant).select("count(participant_id) as total_survey, participant_id, name").group('participant_id, name').page params[:page]
		end
    
	end

	def new
		add_breadcrumb "Eventos", :admin_events_path
    add_breadcrumb "#{@event.title}", :admin_events_path
    add_breadcrumb "#{@research.title}", :admin_event_researches_path
    add_breadcrumb "Questionários", :admin_event_research_surveys_path
    add_breadcrumb "Pesquisadores", :admin_event_research_survey_participants_path
    add_breadcrumb "Inserir Pesquisador"
	end

	def create
		participant = User.find(params["survey_participants"]["participant"])
		surveys_start = params["survey_participants"]["surveys_start"]
		surveys_end = params["survey_participants"]["surveys_end"]

		@surveys.where(number_survey: surveys_start..surveys_end).each do |survey|
			survey.update(participant: participant)
		end

		respond_to do |format|
			format.html { redirect_to admin_event_research_survey_participants_path, notice: 'Participante inserido com sucesso' }
		  format.json { render :show, status: :created, location: admin_event_research_survey_participants_path }
		end
	end

	def edit
		add_breadcrumb "Eventos", :admin_events_path
    add_breadcrumb "#{@event.title}", :admin_events_path
    add_breadcrumb "#{@research.title}", :admin_event_researches_path
    add_breadcrumb "Questionários", :admin_event_research_surveys_path
    add_breadcrumb "Pesquisadores", :admin_event_research_survey_participants_path
    add_breadcrumb "#{@participant.name}", :admin_event_research_survey_participants_path
    add_breadcrumb "Editar"
	end

	def update
		participant = User.find(params["survey_participants"]["participant"])
		surveys_start = params["survey_participants"]["surveys_start"]
		surveys_end = params["survey_participants"]["surveys_end"]

		if @surveys.first.number_survey.to_i == 0
			@surveys = @surveys.where(number_survey: surveys_start..surveys_end)
		else
			@surveys = @surveys.where("(surveys.number_survey)::INT between ? and ?", surveys_start.to_i, surveys_end.to_i)
		end
		if @surveys.update_all(participant_id: participant)

			respond_to do |format|
				format.html { redirect_to admin_event_research_survey_participants_path, notice: 'Participante ataulizado com sucesso' }
			  format.json { render :show, status: :created, location: admin_event_research_survey_participants_path }
			end

		end

	end

	def show
	end

	def destroy
		@survey.each do |survey|
			survey.update(participant_id: nil)
		end

		respond_to do |format|
			format.html { redirect_to admin_event_research_survey_participants_path(@event, @research), notice: 'Participante removido com sucesso' }
		    format.json { render :show, status: :created, location: admin_event_research_survey_participants_path(@event, @research) }
		end

	end

	private	

		def set_users
			if params[:action] == 'edit'
				@users = User.survey_taskers
			else
				@users = User.whithout_participant(@research)
			end
		end

		def set_survey_participant
			@participant = User.find(params[:id])
		end

		def survey_participants_params
	      params.require(:survey_participants).permit(:participant, :survey_start, :survey_end)
	    end

		def set_event_research
      @event = Event.where(status: true).find(params[:event_id])
  	  @research = Research.where(status: true).find(params[:research_id])

  	  if ['edit', 'update'].include? params[:action]
  	  	@surveys = @research.surveys.where("participant_id is null or participant_id = ?", params[:id])
  	  else
  	  	@surveys = @research.surveys.where("participant_id is null")

        if !/\W/.match(@surveys.first.number_survey)
          @surveys = @surveys.order("(number_survey)::INT").page params[:page]
        else
          @surveys = @surveys.order("number_survey").page params[:page]
        end
  	  end
  	  
    end
end

app/helpers/survey_participants_helper.rb
module SurveyParticipantsHelper
end

app/views/admin/survey_participants/_form.html.erb
<label>Pesquisadores</label>
<%= collection_select(:survey_participants, :participant, @users, :id, :name, {selected: @participant.nil? ? "" : @participant.id}) %>		

<fieldset>
	<legend>Questionários</legend>
	<div class="large-6 columns">
		<label for="">Início</label>
		<%= select_tag "survey_participants[surveys_start]", options_from_collection_for_select(@surveys, :number_survey, :number_survey, @surveys.where(participant_id: @participant).first.number_survey)%>
	</div>
	<div class="large-6 columns">
		<label for="">Fim</label>
		<%= select_tag "survey_participants[surveys_end]", options_from_collection_for_select(@surveys, :number_survey, :number_survey, @surveys.where(participant_id: @participant).last.number_survey)%>
	</div>
</fieldset>

<div class="row">
  <div class="large-6 small-6 medium-6 columns">
    <%= link_to 'Cancelar', admin_event_research_survey_participants_path, class: "button hollow radius alert" %>
  </div>
  <div class="large-6 small-6 medium-6 	columns text-right">
    <%= submit_tag "Salvar", class: "button hollow radius" %>
  </div>
</div>

app/views/admin/survey_participants/_participant.html.erb
<% @participants.each do |participant| %>
	<tr>
	  <td><%= participant.name %></td>
	  <td><%= participant.total_survey %></td>
	  <td>
	  	<%= link_to edit_admin_event_research_survey_participant_path(@event, @research, participant.participant_id) do%>
    		<span class="icon-edit radius" data-tooltip aria-haspopup="true" title="Editar"></span>
    	<% end %>
	  </td>
	  <td>
	  	<%= link_to admin_event_research_survey_participant_path(@event, @research, participant.participant_id), method: :delete, data: { confirm: 'Tem certeza que desejar excluir?' } do %>
    		<span class="icon-cancel radius" data-tooltip aria-haspopup="true" title="Excluir"></span>
    	<% end %>
	  </td>
	</tr>
<% end %>

app/views/admin/survey_participants/edit.html.erb
  <div class="row header">
    <div class="large-4 columns end ">
      <span class="icon-calendar"></span>
      <h6>Editar Pesquisador: <em><%= @participant.name %> </em></h6>  
    </div>
  </div>
  <hr>
	
	<div class="row form">
  	<div class="large-12 columns end">
			<%= form_tag admin_event_research_survey_participant_path(@event, @research, @participant), method: :patch do %>
				<%= render 'form' %>
			<% end %>
		</div>
	</div>

app/views/admin/survey_participants/index.html.erb
    <% if flash.any? %>
      <% flash.each do |key, value| %>
        <% if key == 'error'%>
          <div data-alert class="alert-box alert">
            <%= value %>
            <a href="#" class="close">&times;</a>
          </div>
        <% end %>
      <% end %>
    <% end %>
  
    <div class="row header">
      <div class="large-4 small-6 medium-6 columns">
        <span class="icon-paper"></span>
        <h6>Pesquisadores</h6>  
      </div>
      <div class="large-8 small-6 medium-6 columns text-right">
        <%= link_to 'Inserir Pesquisador', new_admin_event_research_survey_participant_path, :class => "button tiny hollow radius icon-plus" %>
      </div>  
    </div>
    
    <div class="row search">
      <%= form_tag admin_event_research_survey_participants_path, method: "get", id: "searchable" do %>
        <div class="large-4 medium-6 columns">
          <%= text_field_tag "search", params[:search] ,placeholder: "Buscar Pesquisadores", class: "radius", data: {type: "event"} %>
        </div>
      <% end %>
    </div>

    <table class="large-12">
      <thead>
        <tr>
          <th>Pesquisador</th>
          <th>Total de Questionários</th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody id="content">
        <%= render "participant", locals: {participants: @participants} %>
      </tbody>
    </table>

app/views/admin/survey_participants/index.js.erb
$("#content").html("<%= escape_javascript(render 'participant', locals: {participants: @participants}) %>");
$('#paginator').html('<%= escape_javascript(paginate(@participants, :remote => true)) %>');

app/views/admin/survey_participants/new.html.erb
  <div class="row header">
    <div class="large-4 columns end ">
      <span class="icon-calendar"></span>
      <h6>Inserir Pesquisador</h6>  
    </div>
  </div>
  <hr>
	
	<div class="row form">
  	<div class="large-12 columns end">
			<%= form_tag admin_event_research_survey_participants_path(@event, @research, @participant) do %>			 
				<%= render 'form' %>
			<% end %>
		</div>
	</div>

app/views/admin/survey_participants/show.html.erb
<div class="large-12 columns content">
  <ul class="breadcrumbs">
    <li><%= link_to 'HOME', admin_root_path%></li>
    <li><%= link_to 'EVENTOS', admin_events_path %></li>
    <li><%= link_to 'PESQUISAS', admin_event_researches_path%></li>
  </ul>
  <div class="large-4 columns">
    <h3>Participante: <b><%= @participant.name %></b></h3>
  </div>
  <div class="large-8 columns text-right">
    <%= link_to 'Back', admin_event_research_survey_participants_path, class: "button tiny"%>
    <%= link_to 'Editar Participante', edit_admin_event_research_survey_participant_path(@event, @research, @participant.id), :class => "button tiny" %>
  </div>
  
  <p id="notice"><%= notice %></p>
  
  <table>
    <thead>
      <tr>
        <th>Questionários</th>
      </tr>
    </thead>

    <tbody>
      <% @survey.each do |survey| %>
        <tr>
          <td><%= survey.number_survey %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>