config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'sign_up' }

  namespace :admin do
    root 'events#index'
    resources :events, path: "eventos" do
      get "report"
      collection do 
        get "search"
      end
      resources :researches, path: "pesquisas" do
        get "report"
        resources :identifiers, path: "identificadores"
        resources :surveys, path: "questionarios", param: :number_survey do
            match 'answers' => 'answers#new', via: :get, path: "respostas"
            match 'answers' => 'answers#create', via: :post, path: "respostas"
            match 'answers' => 'answers#update', via: :patch, path: "respostas"
            match 'answers' => 'answers#update', via: :put, path: "respostas"
            
            collection do
              resources :survey_participants, path: 'participantes'
              match 'import' => 'import_surveys#index',  via: :get, path: "importar"
              match 'import' => 'import_surveys#import', via: :post, path: "importar"
            end
        end
        member do
          match 'groups' => 'groups#index', via: :get, path: "perguntas"
          match 'groups' => 'groups#create', via: :post, path: "perguntas"
          match 'groups' => 'groups#update', via: :patch, path: "perguntas"
          match 'groups' => 'groups#update', via: :put, path: "perguntas"
        end
      end 
    end
    resources :users, path: "usuarios"
  end

  namespace :ajax do 
    get "report", to: "report#index"
    get "identifiers", to: "report#identifiers"
  end

  root 'home#index'
  
end

app/models/event.rb
class Event < ActiveRecord::Base
	enum status: {desativado: 0, ativado: 1}
	belongs_to :author, class_name: "User"
	has_many :researches, dependent: :destroy

	has_many :identifiers

	paginates_per 6
	
	accepts_nested_attributes_for :researches

	validates :title, presence: true

	
	def self.active
		where(status: true)
	end

	def self.for_coordinator(user, search)
		if search.nil? or search.blank?
			where('status = 1 and events.id in (select event_id from researches where status = 1 and researches.id in (select research_id from participants where research_id = researches.id and user_id = ?))', user)
		else
			where('LOWER(title) like LOWER(?) and status = 1 and events.id in (select event_id from researches where status = 1 and researches.id in (select research_id from participants where research_id = researches.id and user_id = ?))', "%#{search}%", user)
		end
	end

	def self.tasker_with_surveys(user, search)
		if !search.nil? and !search.blank?
			where('status = 1 and events.id in (select event_id from researches where status = 1 and researches.id in (select research_id from surveys where surveys.research_id = researches.id and participant_id = ?))', user)
		else
			where('LOWER(title) like LOWER(?) and status = 1 and events.id in (select event_id from researches where status = 1 and researches.id in (select research_id from surveys where surveys.research_id = researches.id and participant_id = ?))', "%#{search}%", user)
		end
	end

	def self.search(search)
    where("LOWER(title) like LOWER(?)", "%#{search}%")
	end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::AdminController
  load_and_authorize_resource
  
  before_action :set_event, only: [:show, :edit, :update, :destroy, :report]
  before_action :get_events, only: [:index, :create, :update]

  # GET /events
  # GET /events.json
  def index
    
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    add_breadcrumb "Eventos", :admin_events_path
    add_breadcrumb "Criar Evento"

    @event = Event.new
  end

  # GET /events/1/edit
  def edit
    add_breadcrumb "Eventos", :admin_events_path
    add_breadcrumb "Editar #{@event.title}", :edit_admin_event_path
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.author = current_user
    
    respond_to do |format|
      if @event.save
        format.html { redirect_to admin_events_path(page: @events.num_pages), notice: 'Evento criado com sucesso' }
        format.json { render :show, status: :created, location: new_admin_event_path(@event) }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    
    @event.status.to_i

    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to admin_events_path(page: get_page(@event, @events)), notice: 'Evento atualizado com sucesso' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.desativado!
    respond_to do |format|
      format.html { redirect_to admin_events_path, notice: 'Evento removido com sucesso' }
      format.json { head :no_content }
    end
  end

  def report
  end

  def search
    if !params[:search].nil? && !params[:search].blank?
      @search = Event.search(params[:search])
    end
    respond_to do |format|
      format.json {render json: @search}
    end
  end

  def sort
    respond_to do |format|
      format.json {render json: @events.order(params[:order])}
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      params[:id] == nil ? @event = Event.find(params[:event_id]) : @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :description, :status, :author_id)
    end

    def get_events
      if params[:sort] == nil 
        params[:sort] = ' created_at desc'
      end


      if current_user.role == "pesquisador"
        @events = Event.tasker_with_surveys(current_user, params[:search]).order(params[:sort]).page params[:page]
      elsif current_user.role == "coordenador"
        @events = Event.for_coordinator(current_user, params[:search]).order(params[:sort]).page params[:page]
      elsif params[:search]
        @events = Event.search(params[:search]).order(params[:sort]).page params[:page]
      else
        @events = Event.active.order(params[:sort]).page params[:page]
      end
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admin/events/_event.html.erb
<tr>
  <td>
    <%= link_to admin_event_researches_path(event) do %>
    <%= event.title.humanize%>
    <span><%= l event.created_at.to_date, format: :long %></span>
    <% end %>
  </td>
  <% # if can? :report, event %>
  <!-- <td class="icon"> -->
    <% # link_to admin_event_report_path(event) do %>
    <!-- <span class="icon-chart-pie radius" data-tooltip aria-haspopup="true" title="Relatório"></span> -->
    <% #end %>
  <!-- </td>  -->
  <% # end %>
  <% if can? :edit, event %>
  <td class="icon">
    <%= link_to edit_admin_event_path(event) do %>
    <span class="icon-edit radius" data-tooltip aria-haspopup="true" title="Editar"></span>
    <% end %>
  </td>
  <% end %>
  <% if can? :destroy, event %>
  <td class="icon">
    <%= link_to admin_event_path(event), class: "sweet", data: {text: "Tem certeza que deseja excluir o evento: #{event.title} ?", title: "Excluir", id: event.id } do %>
    <span class="icon-cancel radius"></span>
    <% end %>
  </td>
  <% end %>
</tr>

app/views/admin/events/_form.html.erb
<div class="row form">
  <div class="large-12 columns end">
    <%= simple_form_for([:admin, @event]) do |f| %>
      <%= f.error_notification %>

      <div class="form-inputs">
        <%= f.input :title, label: "Título", wrapper_html: {class: "large-6"} %>
        <%= f.input :description, label: "Descrição", wrapper_html: {class: "large-6"}  %>
        <% if @event.blank?%>
          <%= f.input :status, collection: Event.statuses.map {|status| [status[0].humanize, status[0]]}, include_blank: false, selected: lambda { |v| v[0].eql? @event.status.humanize},  wrapper_html: {class: "large-3"}  %>
        <% else %>
          <%= f.input :status, collection: Event.statuses.map {|status| [status[0].humanize, status[0]]}, include_blank: false,  wrapper_html: {class: "large-3"}  %>
        <% end %>
      </div>
      
      <div class="row">
        <div class="large-3 small-6 medium-6 columns">
          <%= link_to 'Cancelar', admin_events_path, class: "button hollow radius alert" %>
        </div>
        <div class="large-3 small-6 medium-6 columns text-right end">
          <%= f.submit "Salvar", class: "button hollow radius" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/events/edit.html.erb
  <div class="row header">
    <div class="large-4 columns end ">
      <span class="icon-calendar"></span>
      <h6>Editar Evento</h6>  
    </div>
  </div>
  <hr>
	
  <%= render 'form' %>

app/views/admin/events/index.html.erb
    <% if flash.any? %>
      <% flash.each do |key, value| %>
        <% if key == 'error'%>
          <div data-alert class="alert-box alert">
            <%= value %>
            <a href="#" class="close">&times;</a>
          </div>
        <% end %>
      <% end %>
    <% end %>
    <div class="row collapse header">
      <div class="large-4 small-6 columns">
        <span class="icon-calendar"></span>
        <h6>Eventos</h6>  
      </div>
      <div class="large-8 small-6 columns text-right">
        <% if can? :new, @event %>
          <%= link_to 'Criar Evento', new_admin_event_path, :class => "button tiny hollow radius icon-plus" %>
        <% end %>
      </div>  
    </div>
    
    <div class="row search">
      <%= form_tag admin_events_path, method: "get", id: "searchable" do %>
        <div class="large-4 small-8 columns">
          <%= text_field_tag "search", params[:search] ,placeholder: "Buscar Eventos", class: "radius", data: {type: "event"} %>
        </div>
        <div class="large-1 divider columns"></div>
        <div class="large-2 small-4 columns end">
          <select class="radius" name="sort" id="sortable">
            <option value="">Ordenar por</option>
            <option value="created_at">Data</option>
            <option value="title">Nome</option>
          </select>
        </div>
      <% end %>
    </div>

    <table class="large-12">
      <thead>
        <tr>
          <th>Nome</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody id="content">
        <%= render @events %>
      </tbody>
    </table> 

    
    
    <%= paginate @events, remote: true %>
  </div>
</div>

app/views/admin/events/index.js.erb
$("#content").html("<%= escape_javascript(render(@events)) %>");
$('#paginator').html('<%= escape_javascript(paginate(@events, :remote => true)) %>');

app/views/admin/events/new.html.erb
  <div class="row header">
    <div class="large-4 columns end ">
      <span class="icon-calendar"></span>
      <h6>Novo Evento</h6>  
    </div>
  </div>
  <hr>

	<%= render 'form' %>

app/views/admin/events/report.html.erb
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script>
	google.load('visualization', '1.0', {'packages':['corechart']});
	google.load('visualization', '1.0', {'packages':['corechart']});
</script>

<div class="large-12 columns event">
	<br>
	<h4>Relatório de <%= @event.title %></h4>
	<hr>

	<div class="large-12 large-centered loading columns">
		<h6 class="text-center"><b>Carregado...</b></h6>
		<div id="loadingProgressG" class="large-12 columns large-centered">
			<div id="loadingProgressG_1" class="loadingProgressG"></div>
		</div>
	</div>

	<div class="large-12 columns">		
		<% @event.researches.each{|research| %>
			<div class="panel report hide" research="<%= research.id %>">
				<h4><%= research.title %></h4>
				<hr>
				<% research.groups.sort.each { |group| %>
		    <fieldset>
		      <legend><%= group.title%></legend>
		      <% group.questions.where("type_question <> 0").sort.each { |question| %>
		          <% case question.type_question  
		           when "unica_escolha" %>
		            <div id="question_id_<%= question.id %>">
		              <h6><%= question.title %></h6>
		            </div>
		            <br>
		          <% when "multipla_escolha" %>
		            <div id="question_id_<%= question.id %>">
		              <h6><%= question.title %></h6>
		            </div>
		            <br>
		          <% end %>
		      <% } %>
		    </fieldset>
		  	<% } %>
	  	</div>
  	<% } %>
	</div>
</div>

app/views/admin/events/show.html.erb
<div class="large-12 columns content">
  <ul class="breadcrumbs">
    <li><%= link_to 'EVENTOS', admin_events_path %></li>
  </ul>
  <div class="large-4 columns">
    <h3>Visualizar Evento</h3>
  </div>
  <div class="large-8 columns text-right">
    <%= link_to 'Novo Evento', new_admin_event_path, :class => "button tiny" %>
  </div>
  
  <div class="large-12 columns">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Title:</strong>
    <%= @event.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @event.description %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= @event.status.humanize %>
  </p>

  <p>
    <strong>Author:</strong>
   <%= @event.author_id %>
  </p>

  </div>

  <%= link_to 'Edit', edit_admin_event_path(@event), class: "button tiny info" %> |
  <%= link_to 'Back', admin_events_path, class: "button tiny info" %>
</div>