config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'sign_up' }

  namespace :admin do
    root 'events#index'
    resources :events, path: "eventos" do
      get "report"
      collection do 
        get "search"
      end
      resources :researches, path: "pesquisas" do
        get "report"
        resources :identifiers, path: "identificadores"
        resources :surveys, path: "questionarios", param: :number_survey do
            match 'answers' => 'answers#new', via: :get, path: "respostas"
            match 'answers' => 'answers#create', via: :post, path: "respostas"
            match 'answers' => 'answers#update', via: :patch, path: "respostas"
            match 'answers' => 'answers#update', via: :put, path: "respostas"
            
            collection do
              resources :survey_participants, path: 'participantes'
              match 'import' => 'import_surveys#index',  via: :get, path: "importar"
              match 'import' => 'import_surveys#import', via: :post, path: "importar"
            end
        end
        member do
          match 'groups' => 'groups#index', via: :get, path: "perguntas"
          match 'groups' => 'groups#create', via: :post, path: "perguntas"
          match 'groups' => 'groups#update', via: :patch, path: "perguntas"
          match 'groups' => 'groups#update', via: :put, path: "perguntas"
        end
      end 
    end
    resources :users, path: "usuarios"
  end

  namespace :ajax do 
    get "report", to: "report#index"
    get "identifiers", to: "report#identifiers"
  end

  root 'home#index'
  
end

app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :question
	belongs_to :alternative
	belongs_to :survey

	has_many :alternatives, through: :question 

	accepts_nested_attributes_for :question
	accepts_nested_attributes_for :alternatives
	
end

app/controllers/admin/answers_controller.rb
require 'json'

class Admin::AnswersController < Admin::AdminController
  load_and_authorize_resource
  
  before_action :set_event_research, only: [:show, :edit, :new, :index, :create, :destroy, :update]
  before_action :set_answer, only: [:show, :edit, :update, :destroy]
  # GET /answers
  # GET /answers.json
  def index
    add_breadcrumb "Eventos", :admin_events_path
    add_breadcrumb "#{@event.title}", :admin_events_path
    add_breadcrumb "#{@research.title}", :admin_event_researches_path
    add_breadcrumb "Questionários", :admin_event_research_surveys_path
    add_breadcrumb @survey.number_survey
    add_breadcrumb "Resposta"

  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    p "---------------------------------------------"
    p @survey
    p "---------------------------------------------"
    add_breadcrumb "Eventos", :admin_events_path
    add_breadcrumb "#{@event.title}", :admin_events_path
    add_breadcrumb "#{@research.title}", :admin_event_researches_path
    add_breadcrumb "Questionários", :admin_event_research_surveys_path
    add_breadcrumb @survey.number_survey
    add_breadcrumb "Cadastrar Resposta"
    
  end

  # GET /answers/1/edit
  def edit
    add_breadcrumb "Eventos", :admin_events_path
    add_breadcrumb "#{@event.title}", :admin_events_path
    add_breadcrumb "#{@research.title}", :admin_event_researches_path
    add_breadcrumb "Questionários", :admin_event_research_surveys_path
    add_breadcrumb @survey.number_survey
    add_breadcrumb "Editar Resposta"

    @answer = @survey.answers.first
  end
  # POST /answers
  # POST /answers.json
  def create

    @survey.answers.destroy_all

    params["question"].reject{|a| a == "undefined"}.each do |answer|
      
      question = Question.find(answer[0])
      
      # question text
      if question.type_question == "texto" and answer[1]["alternative"].kind_of? String
        p "question text"
        Answer.create(survey_id: @survey.id, question_id: answer[0], alternative_id: answer[1]["alternative"], value: answer[1]["value"])
      
      elsif answer[1]["alternative"].kind_of? Array
        p "question Array"
        answer[1]["alternative"].reject{|id| id.empty?}.each do |a|
          if Alternative.find(a).as_other == 0
            Answer.create(survey_id: @survey.id, question_id: answer[0], alternative_id: a)
          else
            Answer.create(survey_id: @survey.id, question_id: answer[0], alternative_id: a, value: answer[1]["value"])
          end  
        end
      elsif question.type_question == "unica_escolha" and answer[1]["alternative"].kind_of? String
        p "question unica_escolha"
        if Alternative.find(answer[1]["alternative"]).as_other == 0
          Answer.create(survey_id: @survey.id, question_id: answer[0], alternative_id: answer[1]["alternative"])
        else
          Answer.create(survey_id: @survey.id, question_id: answer[0], alternative_id: answer[1]["alternative"], value: answer[1]["value"])
        end
      else
        p answer[1]
        answer[1].each_with_index do |lista, index|
          p "------------------------------------------------------------------------"
          p lista
          p index
          if lista[1]["status"] != "remove"
            if question.type_question == "texto" and lista[1]["alternative"].kind_of? String
              Answer.create(survey_id: @survey.id, question_id: question.id, alternative_id: lista[1]["alternative"], value: lista[1]["value"], order: index)

            elsif lista[1]["alternative"].kind_of? Array
              lista[1]["alternative"].reject{|id| id.empty?}.each do |a|

                if Alternative.find(a).as_other == 0
                  Answer.create(survey_id: @survey.id, question_id: question.id, alternative_id: a, order: index)
                else
                  Answer.create(survey_id: @survey.id, question_id: question.id, alternative_id: a, value: lista[1]["value"], order: index)
                end  
              end
            elsif question.type_question == "unica_escolha" and lista[1]["alternative"].kind_of? String
              if Alternative.find(lista[1]["alternative"]).as_other == 0
                Answer.create(survey_id: @survey.id, question_id: question.id, alternative_id: lista[1]["alternative"], order: index)
              else
                Answer.create(survey_id: @survey.id, question_id: question.id, alternative_id: lista[1]["alternative"], value: lista[1]["value"], order: index)
              end
            end
          end
          p "------------------------------------------------------------------------" 
        end
      end
    end
    
    respond_to do |format|      
      @survey.update(author: current_user)
      format.html { redirect_to admin_event_research_survey_answers_path, notice: 'Resposta salva com sucesso' }
      format.json { render :show, status: :created, location: @answer }      
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    @survey.answers.destroy_all

    params["question"].reject{|a| a == "undefined"}.each do |answer|
      
      question = Question.find(answer[0])
      
      # question text
      if question.type_question == "texto" and answer[1]["alternative"].kind_of? String
        p "question text"
        p answer
        p answer[0]
        p answer[1]["alternative"]
        Answer.create(survey_id: @survey.id, question_id: answer[0], alternative_id: answer[1]["alternative"], value: answer[1]["value"])
      
      elsif answer[1]["alternative"].kind_of? Array
        p "question Array"
        answer[1]["alternative"].reject{|id| id.empty?}.each do |a|
          if Alternative.find(a).as_other == 0
            Answer.create(survey_id: @survey.id, question_id: answer[0], alternative_id: a)
          else
            Answer.create(survey_id: @survey.id, question_id: answer[0], alternative_id: a, value: answer[1]["value"])
          end  
        end
      elsif question.type_question == "unica_escolha" and answer[1]["alternative"].kind_of? String
        p "question unica_escolha"
        if Alternative.find(answer[1]["alternative"]).as_other == 0
          Answer.create(survey_id: @survey.id, question_id: answer[0], alternative_id: answer[1]["alternative"])
        else
          Answer.create(survey_id: @survey.id, question_id: answer[0], alternative_id: answer[1]["alternative"], value: answer[1]["value"])
        end
      else
        p answer[1]
        answer[1].each_with_index do |lista, index|
          p "------------------------------------------------------------------------"
          p lista
          p index
          
          if lista[1]["status"] != "remove"
            if question.type_question == "texto" and lista[1]["alternative"].kind_of? String
              Answer.create(survey_id: @survey.id, question_id: question.id, alternative_id: lista[1]["alternative"], value: lista[1]["value"], order: index)

            elsif lista[1]["alternative"].kind_of? Array
              lista[1]["alternative"].reject{|id| id.empty?}.each do |a|

                if Alternative.find(a).as_other == 0
                  Answer.create(survey_id: @survey.id, question_id: question.id, alternative_id: a, order: index)
                else
                  Answer.create(survey_id: @survey.id, question_id: question.id, alternative_id: a, value: lista[1]["value"], order: index)
                end  
              end
            elsif question.type_question == "unica_escolha" and lista[1]["alternative"].kind_of? String
              if Alternative.find(lista[1]["alternative"]).as_other == 0
                Answer.create(survey_id: @survey.id, question_id: question.id, alternative_id: lista[1]["alternative"], order: index)
              else
                Answer.create(survey_id: @survey.id, question_id: question.id, alternative_id: lista[1]["alternative"], value: lista[1]["value"], order: index)
              end
            end
          end

          p "------------------------------------------------------------------------" 
        end
      end
    end
    @survey.update(author: current_user)
    respond_to do |format|
        format.html { redirect_to admin_event_research_survey_answers_path(@event, @research, @survey), notice: 'Questionário salvo com sucesso' }
        format.json { render :show, status: :ok, location: @answer }
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to research_answers_path, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_answer
      @answers = @survey.answers.first
    end

    def answer_params
      #params.require(:answer).permit(question: [ :value, :alternative, alternative: [] ])
    end

    def set_event_research
      @event = Event.where(status: 1).find(params[:event_id])
      @research = Research.where(status: 1).find(params[:research_id])
      @survey = @research.surveys.find_by(number_survey: params[:survey_number_survey])
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/admin/answers/_form.html.erb
<p id="notice"><%= notice %></p>

<% if @answer.errors.any? || @survey.errors.any? %>
  <br><br>
  <div id="error_explanation">
    <h2><%= pluralize(@answer.errors.count + @survey.errors.count, "error") %> prohibited this answer from being saved:</h2>

    <ul>
    <% @answer.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    <% @survey.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<h6>Questionário: <%= @survey.number_survey%></h6>

<% if @survey.answers.blank? %>
  <%= form_for([:admin, @event, @research, @survey, @answer]) do |f| %>
    <% @research.groups.order("id ASC").each {|group| %>
      <fieldset>
        <legend><h5><b><%= group.title%></b></h5></legend>
        <% group.questions.where(father_id: nil).each_with_index {|question, index| %>
          <fieldset>
            <legend><h6><%= index + 1 %> - <%= question.title%></h6></legend>
            <%= f.hidden_field :question_id, name: 'answer[question_id][]',value: question.id %>

              <% case question.type_question
                  when "texto"
              %>
              <h6>TEXT</h6>
                    <% question.alternatives.each {|alternative| %>
                      <%= f.text_field :subjective, name: "answer[subjective][#{question.id}][]" %>
                    <% } %>
              <%
                  when "unica_escolha"
              %>
              <h6>UNIC</h6>
                    <%= select_tag "answer[objective][#{question.id}][]", options_for_select(question.alternatives.where("as_other is null or as_other = 0").map {|alternative| [alternative.title,alternative.id] }), :include_blank => true, class: "answer_objective"%>

                    <% question.alternatives.where(as_other: true).each do |alternative| %>
                      <%= f.label alternative.title %>
                      <%= f.text_field :objective, name: "answer[objective][#{question.id}][]", id: "answer_objective_#{question.id}", class: "answer_objective", value: '' %>
                    <% end %>
              <%
                  when "multipla_escolha"
              %>
              <h6>MULTIPLIC</h6>
                    <% question.alternatives.where("as_other is null or as_other = 0").each {|alternative| %>
                      <%= check_box_tag("answer[objective][#{question.id}][]", alternative.id) %>
                      <%= label_tag("answer[objective][#{question.id}][]", alternative.title) %>
                    <% } %>

                    <% question.alternatives.where(as_other: true).each do |alternative| %>
                      <%= f.label alternative.title %>
                      <%= f.text_field :objective, name: "answer[objective][#{question.id}][]", id: "answer_objective_#{question.id}", class: "answer_objective", value: '' %>
                    <% end %>

              <%
                  when "lista"
              %>
                    <table class="large-12">
                      <thead>
                        <tr>
                          <% group.questions.where(father_id: question.id).order(:id).each_with_index do |question_list, index| %>
                            <%= f.hidden_field :question_id, name: 'answer[question_id][]',value: question_list.id %>
                            <td><%= question_list.title %></td>
                          <% end %>
                        </tr>
                      </thead>
                      <tbody>
                        <% for quantity in 1..question.quantity %>
                          <tr>
                            <% group.questions.where(father_id: question.id).order(:id).each_with_index do |question_list, index| %>
                              <td>
                                <% case question_list.type_question 
                                    when "texto"                   
                                %>
                                    <% question_list.alternatives.each {|alternative| %>
                                      <%= f.text_field :subjective, name: "answer[subjective][#{question_list.id}][]" %>
                                    <% } %>
                                <%
                                    when "unica_escolha"
                                %>
                                    <%= select_tag "answer[objective][#{question_list.id}][#{quantity}][]", options_for_select(question_list.alternatives.where("as_other is null or as_other = false").map {|alternative| [alternative.title,alternative.id] }), :include_blank => true, class: "answer_objective"%>
                                <%
                                    when "multipla_escolha"
                                %>
                                    <% question_list.alternatives.where("as_other is null or as_other = false").each {|alternative| %>
                                      <%= check_box_tag("answer[objective][#{question_list.id}][#{quantity}][]", alternative.id) %>
                                      <%= label_tag("answer[objective][#{question_list.id}][#{quantity}][]", alternative.title) %>
                                    <% } %>
                                <% end %>
                                </td>
                            <% end %>
                          </tr>
                        <% end %>
                      </tbody>
                    </table>
              <%
                  end
              %>
              </fieldset>
          <% } %>
      </fieldset>
    <% } %>
    <div class="actions">
      <%= f.submit :class => 'button green'  %>
    </div>
  <% end %>
<% else %>
  <%= form_for([:admin, @event, @research, @survey, @answer], url: admin_event_research_survey_answers_path(@event, @research, @survey, @answer), method: :patch) do |f| %>
    <% @research.groups.order("id ASC").each {|group| %>
      <fieldset>
        <legend><%= group.title%></legend>
        <% group.questions.each { |question| %>

          <% @survey.answers.each_with_index { |answer, index| %>
                <% if answer.question_id == question.id %>
                    <% if !question.father_id? %>
                      <h6><%= question.title %></h6>
                      <%= hidden_field_tag 'answer[question_id][]', question.id %>
                    <% end %>
                  <% case [question.type_question, question.father_id]
                      when ["texto", nil]
                  %>
                    <h6>TEXT</h6>
                      <% question.alternatives.each {|alternative| %>
                        <%= text_field_tag "answer[subjective][#{question.id}][]", answer.subjective.nil? ? '' : answer.subjective %>
                      <% } %>
                  <%
                      when ["unica_escolha", nil]
                  %>
                      <h6>UNIC</h6>
                      <%= select_tag "answer[objective][#{question.id}][]", options_for_select(question.alternatives.where("as_other is null or as_other = 0").map {|alternative| [alternative.title,alternative.id]}, question.alternatives.where("as_other is null or as_other = 0").map{|alternative| answer.objective.include?(alternative.id.to_s) ? alternative.id : ''}), :include_blank => true%>

                      <% question.alternatives.where(as_other: true).each do |alternative| %>
                          <%= f.label alternative.title %>
                          <%= f.text_field :objective, name: "answer[objective][#{question.id}][]", id: "answer_objective_#{question.id}", class: "answer_objective", value: answer.objective.join().to_i > 0 ? "" : answer.objective.join() %>
                      <% end %>
                  <%
                      when ["multipla_escolha", nil]
                  %>
                      <h6>MULTIPLI</h6>
                      <% question.alternatives.where("as_other is null or as_other = 0").each {|alternative| %>
                          <% if answer.objective.include?(alternative.id.to_s) %>
                            <%= check_box_tag("answer[objective][#{question.id}][]", alternative.id, :checked => true) %>
                            <%else%>
                              <%= check_box_tag("answer[objective][#{question.id}][]", alternative.id) %>
                            <%end%>
                            <%= label_tag("answer[objective][#{question.id}][]", alternative.title) %>
                      <% } %>
                      
                      <% question.alternatives.where(as_other: true).each do |alternative| %>
                          <%= f.label alternative.title %>
                          <%= f.text_field :objective, name: "answer[objective][#{question.id}][]", id: "answer_objective_#{question.id}", class: "answer_objective", value: answer.objective.bsearch {|value| value.to_i == 0} %>
                      <% end %>

                  <% 
                      when ["lista", nil]
                  %>
                        <table class="large-12">
                          <thead>
                            <tr>
                              <% group.questions.where(father_id: question.id).order(:id).each_with_index do |question_list, index| %>

                                <%= hidden_field_tag 'answer[question_id][]', question_list.id %>

                                <td><%= question_list.title %></td>
                              <% end %>
                            </tr>
                          </thead>
                          <tbody>
                            <% for quantity in 0...question.quantity %>
                              <tr>
                                <% group.questions.where(father_id: question.id).order(:id).each_with_index do |question_list, index| %>
                                  <td>
                                    <% @survey.answers.where(question_id: question_list.id).each_with_index do |answer_alternative, index| %>
                                      <% case question_list.type_question 
                                          when "texto"                   
                                      %>
                                          <% question_list.alternatives.each {|alternative| %>
                                            <%= text_field_tag "answer[subjective][#{question_list.id}][#{quantity}][]",answer_alternative.subjective.nil? ? '' : answer_alternative.subjective.gsub(/[{}\d"=>\[\]]/, '').split(',')[quantity] %>
                                          <% } %>
                                      <%
                                          when "unica_escolha"
                                      %>
                                          <%= select_tag "answer[objective][#{question_list.id}][#{quantity}][]", options_for_select(question_list.alternatives.where("as_other is null or as_other = false").map {|alternative| [alternative.title,alternative.id]}, question_list.alternatives.where("as_other is null or as_other = false").map{|alternative| if !answer_alternative.objective.empty? then answer_alternative.objective[quantity][1].include?(alternative.id.to_s) ? alternative.id : '' end}), :include_blank => true %>
                                      <% end %>
                                      <% end %>
                                    </td>
                                <% end %>
                              </tr>
                            <% end %>
                          </tbody>
                        </table>
                  <%
                      end
                  %>
                <% end %>
          <% } %>
        <% } %>
      </fieldset>
    <% } %>
    <div class="actions">
      <%= f.submit :class => 'button green'  %>
    </div>
  <% end %>
<% end %>

app/views/admin/answers/edit.html.erb
<div class="large-12 large-centered end columns">
  <div class="large-12">
    <% if flash.any? %>
      <% flash.each do |key, value| %>
        <% if key == 'error'%>
          <div data-alert class="alert-box alert">
            <%= value %>
            <a href="#" class="close">&times;</a>
          </div>
        <% end %>
      <% end %>
    <% end %>
  
    <div class="row header">
      <div class="large-4 columns">
        <span class="icon-calendar"></span>
        <h6>Editar Resposta</h6>  
      </div>
    </div>
    <hr>
    
    <h6 class="survey">Questionário: <%= @survey.number_survey %></h6>

    <div class="large-12 columns large-centered">
      <div class="progress">
        <span class="meter" style="width: <%= 100/@research.groups.count%>%"></span>
      </div>
      
      <%= render 'simple_form' %>
    </div>
  </div>
</div>

app/views/admin/answers/index.html.erb
<div class="large-12 large-centered end columns">
  <div class="large-12">
    <% if flash.any? %>
      <% flash.each do |key, value| %>
        <% if key == 'error'%>
          <div data-alert class="alert-box alert">
            <%= value %>
            <a href="#" class="close">&times;</a>
          </div>
        <% end %>
      <% end %>
    <% end %>
  
    <div class="row header">
      <div class="large-4 columns">
        <span class="icon-calendar"></span>
        <h6>Resposta</h6>  
      </div>
      <div class="large-8 columns text-right">
        <% if can? :edit, Answer%>
          <%= link_to 'Editar', admin_event_research_survey_answers_edit_path(@event, @research, @survey), :class => "button tiny hollow radius icon-edit" %>
        <% end %>
      </div>  
    </div>
    <hr>
    
    <h6 class="survey">Questionário: <%= @survey.number_survey %></h6>

    <div class="large-12 columns large-centered">

      <dl class="tabs" data-tab>
        <% letter = ("A".."Z").to_a %>
        <% @research.groups.sort.each_with_index { |group, index| %>
          
          <dd class="<%= index == 0 ? "active" : "" %>">
            <a href="#group<%= index %>"><%= index + 1 %></a>
          </dd>
        <% } %>  
      </dl>

      <div class="tabs-content">
        <% @research.groups.sort.each_with_index { |group, index| %>
          <div class="content <%= index == 0 ? "active" : "" %>" id="group<%= index %>">
              <h4><strong><%= group.title%></strong></h4>
              <hr>
              <% group.questions.where(father_id: nil).sort.each { |question| %>
                  <% case question.type_question  
                  when "texto" %>
                    <h5><%= question.title %></h5>
                      <p><%= @survey.answers.where(question: question).first.value %></p>
                  <% when "unica_escolha" %>
                    <h5><%= question.title %></h5>
                      <% @survey.answers.where(question: question).sort.each do |answer|%>
                        <% if answer.alternative.as_other == 0 %>
                          <p><%= answer.alternative.title %></p>
                        <% else %>
                          <p><%= answer.alternative.title %>, <%= answer.value %></p>
                        <% end %>
                      <% end %>
                  <% when "multipla_escolha" %>
                    <h5><%= question.title %></h5>
                      <% @survey.answers.where(question: question).sort.each do |answer|%>
                        <% if answer.alternative.as_other == 0 %>
                          <p><%= answer.alternative.title %></p>
                        <% else %>
                          <p><%= answer.alternative.title %>, <%= answer.value %></p>
                        <% end %>
                      <% end %>                  
                  <% when "lista" %>
                    <h5><%= question.title %></h5>
                      <table>
                        <thead>
                          <tr>
                            <% group.questions.where(father_id: question.id).sort.each do |q| %>
                              <td><%= q.title%></td>
                            <% end %>
                          </tr>
                        </thead>
                        <tbody>
                          <tr>
                            <% group.questions.where(father_id: question.id).sort.each do |q| %>
                              <td>
                                <% case q.type_question  
                                when "texto" %>
                                  <p><%= @survey.answers.where(question: q).pluck(:value).join %></p>
                                <% when "unica_escolha" %>
                                  <% @survey.answers.where(question: q).sort.each do |answer|%>
                                    <% if answer.alternative.as_other == 0 %>
                                      <p><%= answer.alternative.title %></p>
                                    <% else %>
                                      <p><%= answer.alternative.title %>, <%= answer.value %></p>
                                    <% end %>
                                  <% end %>
                                <% when "multipla_escolha" %>
                                  <% @survey.answers.where(question: q).sort.each do |answer|%>
                                    <% if answer.alternative.as_other == 0 %>
                                      <p><%= answer.alternative.title %></p>
                                    <% else %>
                                      <p><%= answer.alternative.title %>, <%= answer.value %></p>
                                    <% end %>
                                  <% end %>
                                <% end %>
                              </td>
                            <% end %> 
                          </tr>
                        </tbody>
                      </table>
                  <% end %>
              <% } %>
          </div>
        <% } %>
      </div>
      
    </div>
  </div>
</div>

app/views/admin/answers/new.html.erb
<div class="row header">
    <div class="large-4 columns end ">
      <span class="icon-calendar"></span>
      <h6>Resposta <%= @survey.number_survey %></h6>  
    </div>
  </div>
  <hr>
	<%= render 'simple_form' %>

</div>

app/views/admin/answers/show.html.erb
<div class="large-12 columns content">
  <ul class="breadcrumbs">
    <li><%= link_to @event.title, admin_events_path %></li>
    <li><%= link_to @research.title, admin_event_researches_path%></li>
    <li><%= link_to 'QUESTIONÁRIOS', admin_event_researches_path%></li>
  </ul>
  <div class="large-4 columns">
    <h3>Visualizar Resposta</h3>
  </div>
  <div class="large-8 columns text-right">
    <%= link_to 'Nova Resposta', new_admin_research_answer_path, :class => "button tiny" %>
  </div>

  <p id="notice"><%= notice %></p>

  <p>
    <strong>Research:</strong>
    <%= @answer.research.title %>
  </p>

  <p>
    <strong>Question:</strong>
    <%= @answer.question_id %>
  </p>

  <p>
    <strong>Objective:</strong>
    <%= @answer.objective %>
  </p>

  <p>
    <strong>Subjective:</strong>
    <%= @answer.subjective %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= @answer.author.email %>
  </p>

  <%= link_to 'Edit', edit_admin_research_answer_path(@answer.research, @answer), :class => "button tiny" %> |
  <%= link_to 'Back', admin_research_answers_path, :class => "button tiny" %>
</div>